apiVersion: batch/v1
kind: Job
metadata:
  name: acme-issue
spec:
  parallelism: 1
  completions: 1
  template:         
    metadata:
      name: acme-issue
    spec:
        containers:
        - name: acme-issue
          image: memaldi/openshift-acme
          args: ["--issue",  "-d", "docker-registry-default.apps.openshift.deustotech.eu", "--webroot", "/nginx-root", "--config-home", "/config", "--key-file", "/certs/registry.key", "--fullchain-file", "/certs/registry.crt", "--debug", "--force"]
          volumeMounts:
            - mountPath: /nginx-root
              name: certs
              subPath: nginx-root
            - mountPath: /certs
              name: certs
              subPath: certs
            - mountPath: /config
              name: certs
              subPath: acme-config
        volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        restartPolicy: OnFailure