apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: acme-renew
spec:
  schedule: "0 3 * * *"
  parallelism: 1
  completions: 1
  jobTemplate:
    spec:
        template:
            metadata:
                name: acme-renew
            spec:
                containers:
                - name: acme-renew
                  image: memaldi/openshift-acme
                  args: ["--renew",  "-d", "myapp.example.com", "--webroot", "/nginx-root", "--config-home", "/config", "--key-file", "/certs/server.key", "--fullchain-file", "/certs/server.crt", "--debug", "--force"]
                volumeMounts:
                    - mountPath: /nginx-root
                      name: dbpedia-pvc
                      subPath: nginx-root
                    - mountPath: /certs
                      name: dbpedia-pvc
                      subPath: certs
                    - mountPath: /config
                      name: dbpedia-pvc
                      subPath: acme-config
                volumes:
                - name: dbpedia-pvc
                persistentVolumeClaim:
                    claimName: dbpedia-pvc
                restartPolicy: OnFailure