apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: acme-renew
spec:
  schedule: "0 3 * * *"
  parallelism: 1
  completions: 1
  jobTemplate:
    spec:
        template:
            metadata:
                labels:
                  parent: "acme-renew-cronjob"
            spec:
                containers:
                - name: acme-renew
                  image: memaldi/openshift-acme
                  args: ["--renew",  "-d", "docker-registry-default.apps.openshift.deustotech.eu", "--webroot", "/nginx-root", "--config-home", "/config", "--key-file", "/certs/registry.key", "--fullchain-file", "/certs/registry.crt", "--debug"]
                  volumeMounts:
                      - mountPath: /nginx-root
                        name: certs
                        subPath: nginx-root
                      - mountPath: /certs
                        name: certs
                        subPath: certs
                      - mountPath: /config
                        name: certs
                        subPath: acme-config
                volumes:
                - name: certs
                  persistentVolumeClaim:
                    claimName: certs
                restartPolicy: OnFailure